spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml  # Check the path and ensure it's correct
